#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_OSCAR2_KV, GGML_TYPE_OSCAR2_KV);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_OSCAR2_KV, GGML_TYPE_OSCAR2_KV);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_OSCAR2_KV, GGML_TYPE_OSCAR2_KV);
DECL_FATTN_VEC_CASE(512, GGML_TYPE_OSCAR2_KV, GGML_TYPE_OSCAR2_KV);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_OSCAR2_KV, GGML_TYPE_BF16);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_BF16, GGML_TYPE_OSCAR2_KV);
